DROP SEQUENCE WRITESQ;
DROP TABLE MWRITE;

CREATE SEQUENCE WRITESQ;

CREATE TABLE MWRITE(
WRITENO NUMBER PRIMARY KEY,
ID VARCHAR2(50),
NICKNAME VARCHAR2(50),
TITLE VARCHAR2(1000) NOT NULL,
CONTENT VARCHAR2(2000) NOT NULL,
REGDATE DATE NOT NULL,
DELCHECK VARCHAR2(2) NOT NULL,
ROLE VARCHAR2(10) NOT NULL,


CONSTRAINT FK_ID FOREIGN KEY(ID)
REFERENCES MUSER(ID),

CONSTRAINT CHECK_ROLE2 CHECK(ROLE IN('ADMIN','USER')),
CONSTRAINT CHECK_DELCHECK CHECK(DELCHECK IN('Y','N'))
);

INSERT INTO MWRITE VALUES(WRITESQ.NEXTVAL,'ADMIN01','햄토리','관리자 입니다.','매너를 지켜주세요.',SYSDATE,'Y','ADMIN');
INSERT INTO MWRITE VALUES(WRITESQ.NEXTVAL,'USER01','APPLE','사과','맛있어!',SYSDATE,'Y','USER');

SELECT * FROM MWRITE;